server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://db-path/defaultdb
    username: USERNAME
    password: PASSWORD
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
# request response logging
logging:
  level:
    org.zalando.logbook: TRACE
#  file:
#    path: .
#    name: myapp.log