server:
  port: 8081
spring:
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost;database=TESTDB;encrypt=true;trustServerCertificate=true
    username: sa
    password: P@ssword123
  jpa:
#    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.SQLServer2012Dialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy

# request response logging
logging:
  level:
    org.zalando.logbook: TRACE
  file:
    path: .
    name: myapp.log